services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
